apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: checkvolume
  name: checkvolume
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: checkvolume
    args:
    - sh
    - -c
    - "find /volume/gradle-caches; find /volume/gradle-wrapper"
    volumeMounts:
    - name: volume
      mountPath: /volume
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: cache
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
