apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: jib-gradle-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/coollog/knative-jib
      revision: master
  template:
    name: jib-gradle
    arguments:
    - name: IMAGE
      value: coollog/helloworld-jib:gradle
    - name: CACHE
      value: persistent-cache
    - name: DIRECTORY
      value: subproject

  volumes:
  - name: persistent-cache
    persistentVolumeClaim:
      claimName: cache
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
