apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: jib-maven-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/coollog/knative-jib
      revision: master
  template:
    name: jib-maven
    arguments:
    - name: IMAGE
      value: coollog/helloworld-jib