apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: jib-maven
spec:
  steps:
  - name: build-and-push
    image: gcr.io/cloud-builders/mvn
    args: ['-X', 'compile', 'jib:build']
